# Generated by Django 3.1.2 on 2022-08-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=400)),
                ('release_date', models.CharField(max_length=40)),
                ('lte_exists', models.BooleanField(null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
