name: Django Testing and Deploy

on: 
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      POSTGRES_USER: test_user
      POSTGRES_PASS: test_pwd
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: test_db
      SECRET_KEY: django-insecure-c+rrag-zzkrpwan5@z#mn$d#n4idi#3vvf4wwm+os6!8x-8n(6
      ALLOWED_HOSTS: localhost,127.0.0.1

    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASS}}
          POSTGRES_DB: ${{ env.POSTGRES_DB}}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checking updates for changes
        uses: actions/checkout@v2

      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Installing requirements
        run: |
          pip install -r requirements.txt
      
      - name: Code linting
        run: flake8 main

      # - name: Testing
      #   run: python3 manage.py test
      #   env:
      #     SECRET_KEY: ${{ env.SECRET_KEY}}
      #     DEBUG: "0"
      #     ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS}}
      #     DB_ENGINE: django.db.backends.postgresql
      #     DB_NAME: ${{ env.POSTGRES_DB}}
      #     DB_USER: ${{ env.POSTGRES_USER}}
      #     DB_PASSWORD: ${{ env.POSTGRES_PASS}}
      #     DB_HOST: ${{ env.POSTGRES_HOST}}
      #     DB_PORT: ${{ env.POSTGRES_PORT}}
