version: '3.1'

networks:
  dev_network:

services:

  postgre:
    image: postgres:14.3-alpine3.16
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    networks:
      dev_network:
        aliases:
          - db-postgre

  redis:
      image: redis:7.0.0-alpine3.15
      ports:
        - '6379:6379'
      depends_on:
        - postgre
      networks:
        dev_network:
          aliases:
            - db-redis

  mongo:
    image: mongo:4.4.14
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user_mongo
      MONGO_INITDB_ROOT_PASSWORD: test_password_mongo
    depends_on:
      - redis
    networks:
      dev_network:
        aliases:
          - db-mongo
          